In [1]:
import pandas as pd
import numpy as np

In [2]:
temp = pd.DataFrame({
    'A': [1,2,3,4,np.nan],
    'B': [50,0,250, np.nan, np.nan],
    'C': ['', 'medium', 'low', 'high', 'low'],
    'D': ['Vellore', 'Chennai', 'Trichy', 'Madurai', 'Tiruchirappalli'],
    'E': ['cat', 'dog', None, 'fish', 'egg']
})

In [5]:
df = pd.DataFrame(temp)
df

     A      B       C                D     E
0  1.0   50.0                  Vellore   cat
1  2.0    0.0  medium          Chennai   dog
2  3.0  250.0     low           Trichy  None
3  4.0    NaN    high          Madurai  fish
4  NaN    NaN     low  Tiruchirappalli   egg

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       3 non-null      float64
 2   C       5 non-null      object
 3   D       5 non-null      object
 4   E       4 non-null      object
dtypes: float64(2), object(3)
memory usage: 332.0+ bytes

In [ ]:
df.describe().T

   count   mean        std  min   25%    50%    75%    max
A    5.0    2.5   1.118034  1.0   2.0    2.5    3.0    4.0
B    5.0  100.0  93.541435  0.0  50.0  100.0  100.0  250.0

In [ ]:
df.isna().sum()

A    1
B    2
C    0
D    0
E    1
dtype: int64

In [ ]:
df.isna().sum().sum()

np.int64(4)

## What is Preprocessing of Data ? 

Data preprocessing involves several transformations that are applied to the raw data to make it more amenable for learning. It is carried out before using it for model training or predicton.

There are many pre-processing Steps : 

*   **Data cleaning**
    *   Data Imputation : meaningful replacement of missing values
    *   Duplicate removal : removing duplicate rows from the dataset
    *   Outlier removal : removing outliers from the dataset
    *   Data type conversion : converting data types of features to appropriate types
    
* **Feature engineering** :  is the process of using domain knowledge to extract features form raw data . These features can be used to improve the performance of machine learning algorithms. It is a crucial step in the machine learning pipeline, as the quality and relevance of features can significantly impact the model's predictive power.
    *   **Feature transformation** : `Scaling`, `categorical encoding`,`discretization of continuous features` , `custom transformers` etc.
        *   *Feature scaling* : meaningful scaling of features to a specific range so that they can be compared on the same scale without giveing high importance to any  feature . 
        *   *Encoding categorical features* 
        *   *Discretization of continuous features*
        *   *Custom Transformers*
        *   *Composite Transformers*
            * Apply transformation to diverse features
            * TargetTransformedRegressor
    *  **Feature Construction** : Creating new features from existing features.
        *   *Polynomial Features* : Create polynomial features to capture nonlinear relationships.
        *   *Domain knowledge based feature construction* : Creating new features based on domain knowledge .
            * for Example : area (newfeature)  =  length * breadth

    *   **Feature Selection** : selecting the most useful existing features.
        * Filter based feature selection
        * Wrapper based feature selection

    *   **Feature Extraction**  : Creating completly new features from existing ones. 
        * PCA

> One important nuance: Some textbooks treat feature engineering as a broader, separate stage that includes preprocessing, while others treat it as a part of preprocessing. `So the hierarchy above is a useful learning framework, not a universal rule`.

> Remember:` Data preprocessing` prepares the data; `feature engineering` focuses on making the features more useful for the ML model.

The transformations in a machine learning workflow are applied in a specific order, which can be defined using Scikit-learn's Pipeline. A pipeline can combine preprocessing steps with a final machine learning estimator.

Different types of features often require different transformations. For example, numerical features may require missing-value imputation and scaling, whereas categorical features may require imputation and encoding. Scikit-learn's ColumnTransformer allows us to apply different transformations to different columns or groups of columns and combine their outputs into a single feature matrix.

`FeatureUnion` serves a different purpose: it applies multiple transformers to the same input in parallel and concatenates their outputs into a single feature matrix.

Scikit-learn also provides tools to visualize pipelines, making it easier to understand the sequence of transformations and how the data flows through the machine learning workflow.

## Handling Missing Values Using Median Imputation

In machine learning, missing values must be handled before training a model because most algorithms cannot work with NaN values.

Median imputation is a technique where missing values are replaced with the median of the column.

Why median is used:

  * It is robust to outliers.

  * It works well for skewed numerical data.

  * It does not get affected heavily by extreme values unlike the mean.

This technique is part of the data preprocessing step, which is essential before model training.

In [ ]:
# Replace missing values in column 'A' with the median value of column 'A'
# df['A'].median() calculates the median of all non missing values in column 'A'
# fillna() replaces all NaN values with the computed median
new_A = df['A'].fillna(df['A'].median())

In [ ]:
new_A

0    1.0
1    2.0
2    3.0
3    4.0
4    2.5
Name: A, dtype: float64

In [ ]:
from sklearn.impute import SimpleImputer

## SimpleImputer in Machine Learning

SimpleImputer is a preprocessing utility from sklearn.impute used to handle missing values in datasets.

**Core Concept: Imputation**

Imputation is the process of replacing missing data with substituted values so that machine learning models can work properly.

Key components:

  * missing_values
  
    Specifies what should be considered as missing data. Commonly np.nan.

  * strategy
  
    Determines how missing values are filled. Common strategies include:

    * mean for numerical data

    * median for numerical data

    * most_frequent for categorical or numerical data

    * constant for filling with a fixed value

Why use SimpleImputer instead of manual fillna:

* It integrates smoothly into machine learning pipelines.

* It ensures consistent preprocessing during both training and testing.

* It avoids data leakage when used correctly with train test split.

* This is part of the data preprocessing stage in machine learning workflows

In [ ]:
# Create an instance of SimpleImputer
# missing_values=np.nan specifies that NaN values should be treated as missing
# strategy='median' indicates that missing values will be replaced with the median of the column
si_A = SimpleImputer(missing_values=np.nan, strategy='median')

In [ ]:
si_B = SimpleImputer(missing_values=np.nan, strategy='mean')

- fit
- transform
- fit_transform

In [ ]:
df['A']

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
Name: A, dtype: float64

Pandas returns a **Series** object, not a DataFrame.

**Core Concept: Series**

A Series in pandas is a one dimensional labeled array that can hold data of any type such as integers, floats, or strings.

Why this matters in Machine Learning:

  * Many sklearn functions expect input in two dimensional form.

  * A Series is one dimensional.

  * A DataFrame is two dimensional.

For example:

  * df['A'] → returns a Series

  * df[['A']] → returns a DataFrame

Understanding this difference is important because some preprocessing tools such as SimpleImputer require a two dimensional input.

In [ ]:
print(type(df['A']))

<class 'pandas.core.series.Series'>

In [ ]:
print(type(df[['A']]))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
# Fit the SimpleImputer object on column 'A'
# df[['A']] selects column 'A' as a DataFrame instead of a Series
# fit() computes the median of column 'A' from the training data
# The computed median is stored inside the si_A object for later use
si_A.fit(df[['A']])

SimpleImputer(strategy='median')

In [ ]:
# Apply the learned median value to replace missing values in column 'A'
# df[['A']] ensures the input is two dimensional as required by sklearn
# transform() replaces NaN values using the median calculated during fit()
# The result is returned as a NumPy array
si_A.transform(df[['A']])

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [2.5]])

## fit_transform in Machine Learning

**Core Concept: fit_transform**

The fit_transform method combines two steps into one:

1. fit learns the required parameters from the data

2. transform applies the learned parameters to the same data

In this case:

* fit computes the median of column 'B'

* transform replaces missing values using that median

When to use fit_transform:

* During training data preprocessing

* When you want a shorter and cleaner implementation

When not to use it:

* On test data

Correct workflow:

* Use fit or fit_transform on training data

* Use only transform on test data

This ensures there is no data leakage and the model remains unbiased.

In [ ]:
# Fit the SimpleImputer on column 'B' and immediately transform it
# df[['B']] selects column 'B' as a two dimensional DataFrame
# fit_transform() first calculates the median of column 'B'
# Then it replaces all missing values in column 'B' with the learned median
# The output is returned as a NumPy array
si_B.fit_transform(df[['B']])

array([[ 50.],
       [  0.],
       [250.],
       [100.],
       [100.]])

In [ ]:
from sklearn.impute import KNNImputer

## KNN Imputation

**Core Concept: K Nearest Neighbors Imputation**

KNNImputer is a preprocessing technique from sklearn that fills missing values using the K Nearest Neighbors algorithm.

How it works:

1. For a data point with a missing value, the algorithm finds the K most similar rows based on other available features.

2. It calculates the average value from those nearest neighbors.

3. The missing value is replaced with that average.

In this case:

* n_neighbors=3 means the algorithm will look at the 3 closest rows.

* The missing value will be filled using the mean of those 3 neighbors.

Why use KNN Imputation:

* It preserves relationships between features.

* It can perform better than mean or median imputation when features are correlated.

**Important Note:**

**KNNImputer works based on distance calculations, so feature scaling is often recommended before applying it.**

In [ ]:
# Create an instance of KNNImputer
# n_neighbors=3 means that 3 nearest data points will be used to estimate missing values
# The imputer will replace missing values based on the average of the nearest neighbors
knn_A = KNNImputer(n_neighbors=3)

In [ ]:
knn_A.fit_transform(df[['A']])

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [2.5]])

In [ ]:
knn_B = KNNImputer(n_neighbors=3)

In [ ]:
knn_B.fit_transform(df[['B']])

array([[ 50.],
       [  0.],
       [250.],
       [100.],
       [100.]])

In [ ]:
df

     A      B       C                D     E
0  1.0   50.0                  Vellore   cat
1  2.0    0.0  medium          Chennai   dog
2  3.0  250.0     low           Trichy  None
3  4.0    NaN    high          Madurai  fish
4  NaN    NaN     low  Tiruchirappalli   egg

In [ ]:
si_C = SimpleImputer(missing_values='', strategy='most_frequent')

In [ ]:
si_C.fit_transform(df[['C']])

array([['low'],
       ['medium'],
       ['low'],
       ['high'],
       ['low']], dtype=object)

In [ ]:
df['C'].value_counts()

C
low       2
          1
medium    1
high      1
Name: count, dtype: int64

In [ ]:
# Create an instance of SimpleImputer for handling missing categorical values
# missing_values=None specifies that None values are considered as missing
# strategy='most_frequent' replaces missing values with the most common value in the column
si_E = SimpleImputer(missing_values=None, strategy='most_frequent')

In [ ]:
si_E.fit_transform(df[['E']])

array([['cat'],
       ['dog'],
       ['cat'],
       ['fish'],
       ['egg']], dtype=object)

In [ ]:
df['E'].value_counts()

E
cat     1
dog     1
fish    1
egg     1
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

## One Hot Encoding vs Ordinal Encoding

**Core Concept: Encoding Categorical Variables**

Machine learning models require numerical input. Categorical features must therefore be converted into numbers.

**OneHotEncoder:**

1. Creates a separate binary column for each category.

2. If a column has 3 categories, it becomes 3 new columns.

3. No artificial order is introduced.

4. Suitable for nominal categories such as colors or cities.

Example:
Red, Blue, Green becomes:

Red → 1 0 0

Blue → 0 1 0

Green → 0 0 1

**OrdinalEncoder:**

1. Assigns an integer to each category.

2. Categories are mapped to numbers like 0, 1, 2.

3. Suitable only when categories have a natural order.

Example:
Low, Medium, High becomes:

Low → 0

Medium → 1

High → 2

**Important Note:**

**Using OrdinalEncoder on purely nominal data may introduce unintended ordering relationships, which can negatively affect certain models.**

In [ ]:
# Create an instance of OneHotEncoder
# sparse_output=False ensures the output is returned as a dense NumPy array instead of a sparse matrix
# OneHotEncoder converts categorical values into binary columns
ohe = OneHotEncoder(sparse_output=False)

# Create an instance of OrdinalEncoder
# OrdinalEncoder converts categorical values into integer encoded labels
# Each unique category is assigned a numerical value
oe = OrdinalEncoder()

## Sparse vs Dense Matrix in One Hot Encoding

**Core Concept: Sparse and Dense Matrix Representation**

When using OneHotEncoder, the transformed output can be stored in two formats: sparse or dense.

**Dense Matrix:**

* Stores every value including zeros.

* Represented as a regular NumPy array.

* Takes more memory when there are many zeros.

* Easier to view and manipulate directly.

Example dense output:

1 0 0

0 1 0

0 0 1

**Sparse Matrix:**

* Stores only non zero values.

* Saves memory when the matrix contains many zeros.

* Common in one hot encoding because most values are zero.

* More efficient for high dimensional categorical features.

**Why sparse is useful in One Hot Encoding:**

If a feature has many categories, one hot encoding creates many columns.
For each row, only one column will contain 1 and the rest will be 0.
This results in a matrix filled mostly with zeros.

Using sparse representation:

* Reduces memory usage.

* Improves computational efficiency for large datasets.

In sklearn:

* sparse_output=True returns a sparse matrix.

* sparse_output=False returns a dense NumPy array.

When to use dense:

* Small datasets.

* When easier inspection is needed.

* When the next processing step does not support sparse input.

When to use sparse:

* Large datasets.

* High cardinality categorical features.

* Memory efficiency is important.

In [ ]:
df

     A      B       C                D     E
0  1.0   50.0     low          Vellore   cat
1  2.0    0.0  medium          Chennai   dog
2  3.0  250.0     low           Trichy  None
3  4.0  100.0    high          Madurai  fish
4  2.5  100.0     low  Tiruchirappalli   egg

In [ ]:
ohe.fit_transform(df[['D']])

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
temp1 = pd.DataFrame({
    'A': [1,2,3,4,np.nan],
    'B': [50,0,250, np.nan, np.nan],
    'C': ['', 'medium', 'low', 'high', 'low'],
    'D': ['Vellore', 'Chennai', 'Trichy', 'Madurai', 'Trichy'],
    'E': ['cat', 'dog', None, 'fish', 'egg']
})

In [ ]:
df1 = pd.DataFrame(temp1)

In [ ]:
df1

     A      B       C        D     E
0  1.0   50.0          Vellore   cat
1  2.0    0.0  medium  Chennai   dog
2  3.0  250.0     low   Trichy  None
3  4.0    NaN    high  Madurai  fish
4  NaN    NaN     low   Trichy   egg

In [ ]:
ohe.fit_transform(df1[['D']])

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
ohe.get_feature_names_out()

array(['D_Chennai', 'D_Madurai', 'D_Trichy', 'D_Vellore'], dtype=object)

In [ ]:
df['C'] = df['C'].replace('','low')

In [ ]:
df

     A      B       C                D     E
0  1.0   50.0     low          Vellore   cat
1  2.0    0.0  medium          Chennai   dog
2  3.0  250.0     low           Trichy  None
3  4.0    NaN    high          Madurai  fish
4  NaN    NaN     low  Tiruchirappalli   egg

In [ ]:
oe.fit_transform(df[['C']])

array([[1.],
       [2.],
       [1.],
       [0.],
       [1.]])

## Ordered Encoding with OrdinalEncoder

**Core Concept: Ordinal Encoding with Explicit Category Order**

OrdinalEncoder converts categorical values into integers.
By default, it assigns numbers based on alphabetical order.

However, in many real world problems, categories have a natural ranking.

**Example:**

low < medium < high

If we do not specify the order, the encoder might assign values incorrectly based on alphabetical sorting.

By defining:

categories=`[['low','medium','high']]`

we explicitly control the mapping:

low -> 0

medium -> 1

high -> 2

Why this is important:

Preserves the real world order of categories.

Allows models such as linear regression or logistic regression to interpret increasing magnitude correctly.

Prevents incorrect ordinal relationships.

Use this approach only when categories truly have a meaningful order.

In [ ]:
# Create an OrdinalEncoder with a predefined category order
# categories=[['low','medium','high']] explicitly defines the ranking order
# 'low' will be encoded as 0
# 'medium' will be encoded as 1
# 'high' will be encoded as 2
# This ensures the encoder respects the logical order of the categories
oe1 = OrdinalEncoder(categories=[['low','medium','high']])

In [ ]:
df

     A      B       C                D     E
0  1.0   50.0     low          Vellore   cat
1  2.0    0.0  medium          Chennai   dog
2  3.0  250.0     low           Trichy  None
3  4.0  100.0    high          Madurai  fish
4  2.5  100.0     low  Tiruchirappalli   egg

In [ ]:
oe1.fit_transform(df[['C']])

array([[0.],
       [1.],
       [0.],
       [2.],
       [0.]])

In [ ]:
df['A'] = df['A'].fillna(df['A'].median())

In [ ]:
df['B'] = df['B'].fillna(df['B'].mean())

In [ ]:
df

     A      B       C                D     E
0  1.0   50.0     low          Vellore   cat
1  2.0    0.0  medium          Chennai   dog
2  3.0  250.0     low           Trichy  None
3  4.0  100.0    high          Madurai  fish
4  2.5  100.0     low  Tiruchirappalli   egg

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler

In [ ]:
?OneHotEncoder

In [ ]:
help(OneHotEncoder)     # accessing documentation in the output cell

Help on class OneHotEncoder in module sklearn.preprocessing._encoders:

class OneHotEncoder(_BaseEncoder)
 |  OneHotEncoder(*, categories='auto', drop=None, sparse_output=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None, feature_name_combiner='concat')
 |
 |  Encode categorical features as a one-hot numeric array.
 |
 |  The input to this transformer should be an array-like of integers or
 |  strings, denoting the values taken on by categorical (discrete) features.
 |  The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
 |  encoding scheme. This creates a binary column for each category and
 |  returns a sparse matrix or dense array (depending on the ``sparse_output``
 |  parameter).
 |
 |  By default, the encoder derives the categories based on the unique values
 |  in each feature. Alternatively, you can also specify the `categories`
 |  manually.
 |
 |  This encoding is needed for feeding categorical data to many scikit-learn
 |  estimators, notably linear models and SVMs with the standard kernels.
 |
 |  Note: a one-hot encoding of y labels should use a LabelBinarizer
 |  instead.
 |
 |  Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
 |  For a comparison of different encoders, refer to:
 |  :ref:`sphx_glr_auto_examples_preprocessing_plot_target_encoder.py`.
 |
 |  Parameters
 |  ----------
 |  categories : 'auto' or a list of array-like, default='auto'
 |      Categories (unique values) per feature:
 |
 |      - 'auto' : Determine categories automatically from the training data.
 |      - list : ``categories[i]`` holds the categories expected in the ith
 |        column. The passed categories should not mix strings and numeric
 |        values within a single feature, and should be sorted in case of
 |        numeric values.
 |
 |      The used categories can be found in the ``categories_`` attribute.
 |
 |      .. versionadded:: 0.20
 |
 |  drop : {'first', 'if_binary'} or an array-like of shape (n_features,),             default=None
 |      Specifies a methodology to use to drop one of the categories per
 |      feature. This is useful in situations where perfectly collinear
 |      features cause problems, such as when feeding the resulting data
 |      into an unregularized linear regression model.
 |
 |      However, dropping one category breaks the symmetry of the original
 |      representation and can therefore induce a bias in downstream models,
 |      for instance for penalized linear classification or regression models.
 |
 |      - None : retain all features (the default).
 |      - 'first' : drop the first category in each feature. If only one
 |        category is present, the feature will be dropped entirely.
 |      - 'if_binary' : drop the first category in each feature with two
 |        categories. Features with 1 or more than 2 categories are
 |        left intact.
 |      - array : ``drop[i]`` is the category in feature ``X[:, i]`` that
 |        should be dropped.
 |
 |      When `max_categories` or `min_frequency` is configured to group
 |      infrequent categories, the dropping behavior is handled after the
 |      grouping.
 |
 |      .. versionadded:: 0.21
 |         The parameter `drop` was added in 0.21.
 |
 |      .. versionchanged:: 0.23
 |         The option `drop='if_binary'` was added in 0.23.
 |
 |      .. versionchanged:: 1.1
 |          Support for dropping infrequent categories.
 |
 |  sparse_output : bool, default=True
 |      When ``True``, it returns a :class:`scipy.sparse.csr_matrix`,
 |      i.e. a sparse matrix in "Compressed Sparse Row" (CSR) format.
 |
 |      .. versionadded:: 1.2
 |         `sparse` was renamed to `sparse_output`
 |
 |  dtype : number type, default=np.float64
 |      Desired dtype of output.
 |
 |  handle_unknown : {'error', 'ignore', 'infrequent_if_exist', 'warn'},                      default='error'
 |      Specifies the way unknown categories are handled during :meth:`transform`.
 |
 |      - 'error' : Raise an error if an unknown category is present during transform.
 |      - 'ignore' : When an unknown category is encountered during
 |        transform, the resulting one-hot encoded columns for this feature
 |        will be all zeros. In the inverse transform, an unknown category
 |        will be denoted as None.
 |      - 'infrequent_if_exist' : When an unknown category is encountered
 |        during transform, the resulting one-hot encoded columns for this
 |        feature will map to the infrequent category if it exists. The
 |        infrequent category will be mapped to the last position in the
 |        encoding. During inverse transform, an unknown category will be
 |        mapped to the category denoted `'infrequent'` if it exists. If the
 |        `'infrequent'` category does not exist, then :meth:`transform` and
 |        :meth:`inverse_transform` will handle an unknown category as with
 |        `handle_unknown='ignore'`. Infrequent categories exist based on
 |        `min_frequency` and `max_categories`. Read more in the
 |        :ref:`User Guide <encoder_infrequent_categories>`.
 |      - 'warn' : When an unknown category is encountered during transform
 |        a warning is issued, and the encoding then proceeds as described for
 |        `handle_unknown="infrequent_if_exist"`.
 |
 |      .. versionchanged:: 1.1
 |          `'infrequent_if_exist'` was added to automatically handle unknown
 |          categories and infrequent categories.
 |
 |      .. versionadded:: 1.6
 |         The option `"warn"` was added in 1.6.
 |
 |  min_frequency : int or float, default=None
 |      Specifies the minimum frequency below which a category will be
 |      considered infrequent.
 |
 |      - If `int`, categories with a smaller cardinality will be considered
 |        infrequent.
 |
 |      - If `float`, categories with a smaller cardinality than
 |        `min_frequency * n_samples`  will be considered infrequent.
 |
 |      .. versionadded:: 1.1
 |          Read more in the :ref:`User Guide <encoder_infrequent_categories>`.
 |
 |  max_categories : int, default=None
 |      Specifies an upper limit to the number of output features for each input
 |      feature when considering infrequent categories. If there are infrequent
 |      categories, `max_categories` includes the category representing the
 |      infrequent categories along with the frequent categories. If `None`,
 |      there is no limit to the number of output features.
 |
 |      .. versionadded:: 1.1
 |          Read more in the :ref:`User Guide <encoder_infrequent_categories>`.
 |
 |  feature_name_combiner : "concat" or callable, default="concat"
 |      Callable with signature `def callable(input_feature, category)` that returns a
 |      string. This is used to create feature names to be returned by
 |      :meth:`get_feature_names_out`.
 |
 |      `"concat"` concatenates encoded feature name and category with
 |      `feature + "_" + str(category)`.E.g. feature X with values 1, 6, 7 create
 |      feature names `X_1, X_6, X_7`.
 |
 |      .. versionadded:: 1.3
 |
 |  Attributes
 |  ----------
 |  categories_ : list of arrays
 |      The categories of each feature determined during fitting
 |      (in order of the features in X and corresponding with the output
 |      of ``transform``). This includes the category specified in ``drop``
 |      (if any).
 |
 |  drop_idx_ : array of shape (n_features,)
 |      - ``drop_idx_[i]`` is the index in ``categories_[i]`` of the category
 |        to be dropped for each feature.
 |      - ``drop_idx_[i] = None`` if no category is to be dropped from the
 |        feature with index ``i``, e.g. when `drop='if_binary'` and the
 |        feature isn't binary.
 |      - ``drop_idx_ = None`` if all the transformed features will be
 |        retained.
 |
 |      If infrequent categories are enabled by setting `min_frequency` or
 |      `max_categories` to a non-default value and `drop_idx[i]` corresponds
 |      to a infrequent category, then the entire infrequent category is
 |      dropped.
 |
 |      .. versionchanged:: 0.23
 |         Added the possibility to contain `None` values.
 |
 |  infrequent_categories_ : list of ndarray
 |      Defined only if infrequent categories are enabled by setting
 |      `min_frequency` or `max_categories` to a non-default value.
 |      `infrequent_categories_[i]` are the infrequent categories for feature
 |      `i`. If the feature `i` has no infrequent categories
 |      `infrequent_categories_[i]` is None.
 |
 |      .. versionadded:: 1.1
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 1.0
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  feature_name_combiner : callable or None
 |      Callable with signature `def callable(input_feature, category)` that returns a
 |      string. This is used to create feature names to be returned by
 |      :meth:`get_feature_names_out`.
 |
 |      .. versionadded:: 1.3
 |
 |  See Also
 |  --------
 |  OrdinalEncoder : Performs an ordinal (integer)
 |    encoding of the categorical features.
 |  TargetEncoder : Encodes categorical features using the target.
 |  sklearn.feature_extraction.DictVectorizer : Performs a one-hot encoding of
 |    dictionary items (also handles string-valued features).
 |  sklearn.feature_extraction.FeatureHasher : Performs an approximate one-hot
 |    encoding of dictionary items or strings.
 |  LabelBinarizer : Binarizes labels in a one-vs-all
 |    fashion.
 |  MultiLabelBinarizer : Transforms between iterable of
 |    iterables and a multilabel format, e.g. a (samples x classes) binary
 |    matrix indicating the presence of a class label.
 |
 |  Examples
 |  --------
 |  Given a dataset with two features, we let the encoder find the unique
 |  values per feature and transform the data to a binary one-hot encoding.
 |
 |  >>> from sklearn.preprocessing import OneHotEncoder
 |
 |  One can discard categories not seen during `fit`:
 |
 |  >>> enc = OneHotEncoder(handle_unknown='ignore')
 |  >>> X = [['Male', 1], ['Female', 3], ['Female', 2]]
 |  >>> enc.fit(X)
 |  OneHotEncoder(handle_unknown='ignore')
 |  >>> enc.categories_
 |  [array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
 |  >>> enc.transform([['Female', 1], ['Male', 4]]).toarray()
 |  array([[1., 0., 1., 0., 0.],
 |         [0., 1., 0., 0., 0.]])
 |  >>> enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])
 |  array([['Male', 1],
 |         [None, 2]], dtype=object)
 |  >>> enc.get_feature_names_out(['gender', 'group'])
 |  array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'], ...)
 |
 |  One can always drop the first column for each feature:
 |
 |  >>> drop_enc = OneHotEncoder(drop='first').fit(X)
 |  >>> drop_enc.categories_
 |  [array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
 |  >>> drop_enc.transform([['Female', 1], ['Male', 2]]).toarray()
 |  array([[0., 0., 0.],
 |         [1., 1., 0.]])
 |
 |  Or drop a column for feature only having 2 categories:
 |
 |  >>> drop_binary_enc = OneHotEncoder(drop='if_binary').fit(X)
 |  >>> drop_binary_enc.transform([['Female', 1], ['Male', 2]]).toarray()
 |  array([[0., 1., 0., 0.],
 |         [1., 0., 1., 0.]])
 |
 |  One can change the way feature names are created.
 |
 |  >>> def custom_combiner(feature, category):
 |  ...     return str(feature) + "_" + type(category).__name__ + "_" + str(category)
 |  >>> custom_fnames_enc = OneHotEncoder(feature_name_combiner=custom_combiner).fit(X)
 |  >>> custom_fnames_enc.get_feature_names_out()
 |  array(['x0_str_Female', 'x0_str_Male', 'x1_int_1', 'x1_int_2', 'x1_int_3'],
 |        dtype=object)
 |
 |  Infrequent categories are enabled by setting `max_categories` or `min_frequency`.
 |
 |  >>> import numpy as np
 |  >>> X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
 |  >>> ohe = OneHotEncoder(max_categories=3, sparse_output=False).fit(X)
 |  >>> ohe.infrequent_categories_
 |  [array(['a', 'd'], dtype=object)]
 |  >>> ohe.transform([["a"], ["b"]])
 |  array([[0., 0., 1.],
 |         [1., 0., 0.]])
 |
 |  Method resolution order:
 |      OneHotEncoder
 |      _BaseEncoder
 |      sklearn.base.TransformerMixin
 |      sklearn.utils._set_output._SetOutputMixin
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._estimator_html_repr._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *, categories='auto', drop=None, sparse_output=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None, feature_name_combiner='concat')
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit(self, X, y=None)
 |      Fit OneHotEncoder to X.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          The data to determine the categories of each feature.
 |
 |      y : None
 |          Ignored. This parameter exists only for compatibility with
 |          :class:`~sklearn.pipeline.Pipeline`.
 |
 |      Returns
 |      -------
 |      self
 |          Fitted encoder.
 |
 |  get_feature_names_out(self, input_features=None)
 |      Get output feature names for transformation.
 |
 |      Parameters
 |      ----------
 |      input_features : array-like of str or None, default=None
 |          Input features.
 |
 |          - If `input_features` is `None`, then `feature_names_in_` is
 |            used as feature names in. If `feature_names_in_` is not defined,
 |            then the following input feature names are generated:
 |            `["x0", "x1", ..., "x(n_features_in_ - 1)"]`.
 |          - If `input_features` is an array-like, then `input_features` must
 |            match `feature_names_in_` if `feature_names_in_` is defined.
 |
 |      Returns
 |      -------
 |      feature_names_out : ndarray of str objects
 |          Transformed feature names.
 |
 |  inverse_transform(self, X)
 |      Convert the data back to the original representation.
 |
 |      When unknown categories are encountered (all zeros in the
 |      one-hot encoding), ``None`` is used to represent this category. If the
 |      feature with the unknown category has a dropped category, the dropped
 |      category will be its inverse.
 |
 |      For a given input feature, if there is an infrequent category,
 |      'infrequent_sklearn' will be used to represent the infrequent category.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape                 (n_samples, n_encoded_features)
 |          The transformed data.
 |
 |      Returns
 |      -------
 |      X_tr : ndarray of shape (n_samples, n_features)
 |          Inverse transformed array.
 |
 |  transform(self, X)
 |      Transform X using one-hot encoding.
 |
 |      If `sparse_output=True` (default), it returns an instance of
 |      :class:`scipy.sparse._csr.csr_matrix` (CSR format).
 |
 |      If there are infrequent categories for a feature, set by specifying
 |      `max_categories` or `min_frequency`, the infrequent categories are
 |      grouped into a single category.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          The data to encode.
 |
 |      Returns
 |      -------
 |      X_out : {ndarray, sparse matrix} of shape                 (n_samples, n_encoded_features)
 |          Transformed input. If `sparse_output=True`, a sparse matrix will be
 |          returned.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {'_parameter_constraints': <class 'dict'>}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from _BaseEncoder:
 |
 |  __sklearn_tags__(self)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from _BaseEncoder:
 |
 |  infrequent_categories_
 |      Infrequent categories for each feature.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.TransformerMixin:
 |
 |  fit_transform(self, X, y=None, **fit_params)
 |      Fit to data, then transform it.
 |
 |      Fits transformer to `X` and `y` with optional parameters `fit_params`
 |      and returns a transformed version of `X`.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Input samples.
 |
 |      y :  array-like of shape (n_samples,) or (n_samples, n_outputs),                 default=None
 |          Target values (None for unsupervised transformations).
 |
 |      **fit_params : dict
 |          Additional fit parameters.
 |
 |      Returns
 |      -------
 |      X_new : ndarray array of shape (n_samples, n_features_new)
 |          Transformed array.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.utils._set_output._SetOutputMixin:
 |
 |  set_output(self, *, transform=None)
 |      Set output container.
 |
 |      See :ref:`sphx_glr_auto_examples_miscellaneous_plot_set_output.py`
 |      for an example on how to use the API.
 |
 |      Parameters
 |      ----------
 |      transform : {"default", "pandas", "polars"}, default=None
 |          Configure output of `transform` and `fit_transform`.
 |
 |          - `"default"`: Default output format of a transformer
 |          - `"pandas"`: DataFrame output
 |          - `"polars"`: Polars output
 |          - `None`: Transform configuration is unchanged
 |
 |          .. versionadded:: 1.4
 |              `"polars"` option was added.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from sklearn.utils._set_output._SetOutputMixin:
 |
 |  __init_subclass__(auto_wrap_output_keys=('transform',), **kwargs)
 |      Set the ``set_{method}_request`` methods.
 |
 |      This uses PEP-487 [1]_ to set the ``set_{method}_request`` methods. It
 |      looks for the information available in the set default values which are
 |      set using ``__metadata_request__*`` class attributes, or inferred
 |      from method signatures.
 |
 |      The ``__metadata_request__*`` class attributes are used when a method
 |      does not explicitly accept a metadata through its arguments or if the
 |      developer would like to specify a request value for those metadata
 |      which are different from the default ``None``.
 |
 |      References
 |      ----------
 |      .. [1] https://www.python.org/dev/peps/pep-0487
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.utils._set_output._SetOutputMixin:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |      Helper for pickle.
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  __sklearn_clone__(self)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |

## Feature Scaling in Machine Learning

**Core Concept: Feature Scaling**

Feature scaling ensures that numerical features are on a similar scale so that machine learning models perform efficiently and fairly.

1. StandardScaler

    Formula:

    **z = (x − mean) / standard deviation**

* Transforms data to have mean 0 and standard deviation 1.

* Useful for algorithms based on distance or gradient descent.

* Commonly used in logistic regression, SVM, and KNN.

2. MinMaxScaler

    Formula:

    **x_scaled = (x − min) / (max − min)**

* Scales data into a fixed range, typically 0 to 1.

* Preserves the shape of the original distribution.

* Sensitive to outliers.

3. MaxAbsScaler

    Formula:

    **x_scaled = x / max absolute value**

* Scales values to range between −1 and 1.

* Does not shift or center data.

* Works well with sparse matrices because it does not destroy sparsity.

**Why scaling matters:**

**Many algorithms such as KNN, SVM, and gradient based models are sensitive to feature magnitude. Without scaling, features with larger values can dominate the model.**

In [ ]:
# Create an instance of StandardScaler
# StandardScaler standardizes features by removing the mean and scaling to unit variance
# Each feature will have mean equal to 0 and standard deviation equal to 1
ss = StandardScaler()

# Create an instance of MinMaxScaler
# MinMaxScaler scales features to a fixed range, usually between 0 and 1
# It rescales the data based on the minimum and maximum values of each feature
mms = MinMaxScaler()

# Create an instance of MaxAbsScaler
# MaxAbsScaler scales each feature by dividing by its maximum absolute value
# It preserves zero entries and is useful for sparse data
mas = MaxAbsScaler()

In [ ]:
ss.fit_transform(df[['A', 'B']])

array([[-1.5       , -0.5976143 ],
       [-0.5       , -1.19522861],
       [ 0.5       ,  1.79284291],
       [ 1.5       ,  0.        ],
       [ 0.        ,  0.        ]])

In [ ]:
mms.fit_transform(df[['A', 'B']])

array([[0.        , 0.2       ],
       [0.33333333, 0.        ],
       [0.66666667, 1.        ],
       [1.        , 0.4       ],
       [0.5       , 0.4       ]])

In [ ]:
mas.fit_transform(df[['A', 'B']])

array([[0.25 , 0.2  ],
       [0.5  , 0.   ],
       [0.75 , 1.   ],
       [1.   , 0.4  ],
       [0.625, 0.4  ]])

# Questions

Dataset: https://drive.google.com/file/d/1JYQ_dmlNobUgaRc-xwjsIALurJiW6eHg/view

In [ ]:
data = pd.read_csv('/content/data.csv')

In [ ]:
data.head()

,customer_id,name,age,gender,email,join_date,last_purchase,total_spent,purchase_count,country,city,postal_code,subscription_type,credit_score,is_active,payment_method,preferred_category,avg_session_duration,device_type,campaign_response
0,4d623250-b704-4df8-aea2-5403458a1d6e,Sean Nelson,41,F,tylersmith@example.org,"Dec 19, 2020",2025-04-02,238.517142,51.0,Germany,Port Michaelmouth,06803,Corporate,663,True,NaN,Groceries,1066.626690,TABLET,NaN
1,e5593c2b-1ed8-4fe8-be82-acced82f9711,Eddie Wood,38,Female,xreed@example.net,30/10/2021,2024-12-25,93.126377,31.0,USA,Brig...,64245,NaN,656,N,PayPal,Clothing,327.762945,mobile,no
2,7240c499-1c3d-4188-8b12-76c515aff931,Abigail Graham,11,M,cartersara@example.com,"May 03, 2022",2025-05-10,873.017713,87.0,Germany,Port Kevinton,43574,Trial,672,N,Cryptocurrency,Clothing,95.654242,Mobile,No
3,43c7001d-4c6d-4011-aa02-e9b57c0e3944,Jessica Contreras,40,NaN,fsalazar@example.org,"Aug 03, 2021",NaN,401.703726,NaN,India,Gillespietown,NaN,Trial,614,True,PayPal,Home,498.371991,mobile,NaN
4,4fb0f886-7e67-4982-bfe0-959272cece1b,Kelly Olson,20,Female,robert21@example.org,"Apr 05, 2024",2025-05-07,1198.186419,34.0,Germany,jamesberg,82358,Premium,692,N,Bank Transfer,Groceries,NaN,mobile,YES

In [ ]:
data.shape

(10000, 20)

In [ ]:
data.isna().sum()

customer_id                0
name                     959
age                        0
gender                  1380
email                      0
join_date                  0
last_purchase           1530
total_spent                0
purchase_count           941
country                 1567
city                       0
postal_code             2477
subscription_type       2037
credit_score               0
is_active                  0
payment_method          1671
preferred_category      2125
avg_session_duration    2023
device_type                0
campaign_response       1992
dtype: int64

* `postal_code`: Imputing with mode (most common postal code)
* `campaign_response` : Create a new category as 'missing_response'.
* `age`: Impute with median

In [ ]:
si_postal = SimpleImputer(strategy='most_frequent')
si_campaign = SimpleImputer(strategy='constant', fill_value='missing_response')
si_age = SimpleImputer(strategy='median')

In [ ]:
si_postal.fit_transform(data[['postal_code']])

array([['06803'],
       ['64245'],
       ['43574'],
       ...,
       ['33931'],
       ['70357'],
       ['AB-123']], dtype=object)

In [ ]:
si_campaign.fit_transform(data[['campaign_response']])

array([['missing_response'],
       ['no'],
       ['No'],
       ...,
       ['No'],
       ['YES'],
       ['No']], dtype=object)

In [ ]:
si_age.fit_transform(data[['age']])

array([[41.],
       [38.],
       [11.],
       ...,
       [35.],
       [59.],
       [40.]])