In [263]:
import pandas as pd
import numpy as np

# Pandas Exercises

## Exercise 1: Sales Data Analysis

### Purpose of the Code Cell

This code cell generates a synthetic sales dataset using random values. The goal is to simulate real world transactional data for analysis, visualization, or practice in data manipulation.

Step by Step Functionality

First, a random seed is set to ensure reproducibility. This guarantees that the randomly generated data will be the same each time the code runs.

A date range covering three months is created. Lists of product names and regions are also defined to represent categorical sales information.

A DataFrame named sales_data is then constructed with 500 rows. Each column is populated using random selection or random number generation:

* Date is randomly chosen from the predefined date range.

* Product and Region are randomly selected from their respective lists.

* Units_Sold contains random integer values representing quantity sold.

* Unit_Price contains random floating point values representing product price.

* Customer_ID contains random customer identifiers.

Finally, a new column called Total_Sales is computed by multiplying Units_Sold with Unit_Price. This represents the total revenue generated per transaction.

In [264]:
np.random.seed(42)  # Set a seed for reproducibility so random results remain the same each run

dates = pd.date_range('2023-01-01', '2023-03-31')  # Create a date range from Jan 1, 2023 to Mar 31, 2023
products = ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard']  # List of product names
regions = ['North', 'South', 'East', 'West']  # List of sales regions

sales_data = pd.DataFrame({  # Create a DataFrame with randomly generated sales data
    'Date': np.random.choice(dates, 500),  # Randomly select 500 dates from the date range
    'Product': np.random.choice(products, 500),  # Randomly select 500 products
    'Region': np.random.choice(regions, 500),  # Randomly select 500 regions
    'Units_Sold': np.random.randint(1, 20, 500),  # Generate 500 random integers between 1 and 19 for units sold
    'Unit_Price': np.random.uniform(100, 2000, 500).round(2),  # Generate 500 random prices between 100 and 2000 rounded to 2 decimals
    'Customer_ID': np.random.randint(1000, 1100, 500)  # Generate 500 random customer IDs between 1000 and 1099
})

sales_data['Total_Sales'] = sales_data['Units_Sold'] * sales_data['Unit_Price']  # Create a new column by multiplying units sold with unit price

In [265]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

In [266]:
sales_data['Total_Sales']

0      23386.68
1      18033.15
2       5247.27
3      14186.77
4      11265.60
         ...
495     4445.10
496    15058.44
497     9508.62
498     3522.20
499    19245.78
Name: Total_Sales, Length: 500, dtype: float64

In [267]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

In [268]:
# sales_data.head(9)
sales_data.sample(9)

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
57,2023-03-12,Tablet,East,12,1258.68,1060,15104.16
180,2023-01-03,Tablet,West,13,1316.32,1057,17112.16
431,2023-01-01,Laptop,West,5,1159.85,1086,5799.25
183,2023-01-27,Laptop,East,10,1392.25,1038,13922.50
5,2023-03-24,Phone,North,10,1111.27,1003,11112.70
408,2023-03-01,Phone,East,4,183.10,1096,732.40
49,2023-03-01,Keyboard,East,2,1767.99,1069,3535.98
210,2023-01-19,Tablet,South,15,1500.64,1058,22509.60
226,2023-03-11,Keyboard,South,4,758.01,1078,3032.04

In [269]:
sales_data.describe()

,Date,Units_Sold,Unit_Price,Customer_ID,Total_Sales
count,500,500.000000,500.000000,500.000000,500.000000
mean,2023-02-13 07:26:23.999999744,10.054000,1038.592700,1049.500000,10346.006300
min,2023-01-01 00:00:00,1.000000,100.630000,1000.000000,124.160000
25%,2023-01-22 00:00:00,5.000000,562.865000,1024.000000,3608.475000
50%,2023-02-13 12:00:00,10.000000,1057.750000,1049.000000,8299.140000
75%,2023-03-05 00:00:00,15.000000,1513.830000,1073.000000,15261.470000
max,2023-03-31 00:00:00,19.000000,1991.410000,1099.000000,34340.580000
std,NaN,5.393446,536.397786,28.644214,8101.725382

In [270]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         500 non-null    datetime64[ns]
 1   Product      500 non-null    object
 2   Region       500 non-null    object
 3   Units_Sold   500 non-null    int32
 4   Unit_Price   500 non-null    float64
 5   Customer_ID  500 non-null    int32
 6   Total_Sales  500 non-null    float64
dtypes: datetime64[ns](1), float64(2), int32(2), object(2)
memory usage: 23.6+ KB

**Purpose of the Code Cell**

This code cell checks for missing values in the dataset and ranks the columns based on the number of missing entries.

**Step by Step Functionality**

The isna method identifies missing values in each column of the DataFrame. It returns a boolean DataFrame where True represents a missing value.

The sum method counts the number of True values in each column, giving the total number of missing values per column.

The sort_values method then arranges the results in descending order so that columns with the highest number of missing values appear first.

In [271]:
sales_data.isna()

      Date  Product  Region  Units_Sold  Unit_Price  Customer_ID  Total_Sales
0    False    False   False       False       False        False        False
1    False    False   False       False       False        False        False
2    False    False   False       False       False        False        False
3    False    False   False       False       False        False        False
4    False    False   False       False       False        False        False
..     ...      ...     ...         ...         ...          ...          ...
495  False    False   False       False       False        False        False
496  False    False   False       False       False        False        False
497  False    False   False       False       False        False        False
498  False    False   False       False       False        False        False
499  False    False   False       False       False        False        False

[500 rows x 7 columns]

In [272]:
sales_data.isna().sum()

# sum -> axis argument axis = 0  Column-wise sum, axis = 1 Row-wise sum  bydefault axis = 0

Date           0
Product        0
Region         0
Units_Sold     0
Unit_Price     0
Customer_ID    0
Total_Sales    0
dtype: int64

In [273]:
sales_data.isna().sum().sort_values(ascending=False)
# Check for missing values in each column
# isna() returns True for missing values
# sum() counts the total missing values per column
# sort_values(ascending=False) sorts the result in descending order

Date           0
Product        0
Region         0
Units_Sold     0
Unit_Price     0
Customer_ID    0
Total_Sales    0
dtype: int64

In [274]:
sales_data.shape

(500, 7)

### Tasks:

1. **Basic Indexing**:
   - Select all sales from the 'North' region
   - Select sales of 'Laptop' or 'Phone' with more than 10 units sold
   - Select columns 'Product', 'Region', and 'Total_Sales' for all records

2. **Grouping Operations**:
   - Find the total sales by product
   - Calculate the average units sold by region
   - Find the top 3 customers by total spending

3. **Filtering**:
   - Find all sales above $5000
   - Find the most expensive single sale for each product
   - Find all sales that occurred on weekends

4. **Apply Functions**:
   - Create a new column 'Price_Category' that labels each sale as:
     - 'Budget' if Unit_Price < 300
     - 'Mid-Range' if 300 ≤ Unit_Price < 1000
     - 'Premium' if Unit_Price ≥ 1000

In [275]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

In [276]:

sales_data['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

### 1.1

In [277]:
sales_data.Region.value_counts()
sales_data[sales_data.Region == 'North'].shape[0]  ## all the diff sales  at the North region

134

In [278]:
sales_data['Region']

0      North
1      South
2      North
3      North
4      North
       ...
495    South
496     West
497    North
498    South
499    North
Name: Region, Length: 500, dtype: object

In [279]:
sales_data[sales_data['Region']=='North']

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
5,2023-03-24,Phone,North,10,1111.27,1003,11112.70
...,...,...,...,...,...,...,...
489,2023-02-20,Tablet,North,5,361.86,1020,1809.30
490,2023-02-12,Tablet,North,1,1359.78,1068,1359.78
492,2023-03-08,Tablet,North,19,438.91,1019,8339.29
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

### 1.2

In [280]:
sales_data.Product.unique()

array(['Keyboard', 'Monitor', 'Phone', 'Tablet', 'Laptop'], dtype=object)

In [281]:
?sales_data.Product.isin
# Use the question mark to display the documentation of the isin method
# sales_data.Product selects the Product column from the DataFrame
# isin is a method that checks whether each value exists in a given list or set

Signature: sales_data.Product.isin(values) -> 'Series'
Docstring:
Whether elements in Series are contained in `values`.

Return a boolean Series showing whether each element in the Series
matches an element in the passed sequence of `values` exactly.

Parameters
----------
values : set or list-like
    The sequence of values to test. Passing in a single string will
    raise a ``TypeError``. Instead, turn a single string into a
    list of one element.

Returns
-------
Series
    Series of booleans indicating if each element is in values.

Raises
------
TypeError
  * If `values` is a string

See Also
--------
DataFrame.isin : Equivalent method on DataFrame.

Examples
--------
>>> s = pd.Series(['llama', 'cow', 'llama', 'beetle', 'llama',
...                'hippo'], name='animal')
>>> s.isin(['cow', 'llama'])
0     True
1     True
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

To invert the boolean values, use the ``~`` operator:

>>> ~s.isin(['cow', 'llama'])
0    False
1    False
2    False
3     True
4    False
5     True
Name: animal, dtype: bool

Passing a single string as ``s.isin('llama')`` will raise an error. Use
a list of one element instead:

>>> s.isin(['llama'])
0     True
1    False
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

Strings and integers are distinct and are therefore not comparable:

>>> pd.Series([1]).isin(['1'])
0    False
dtype: bool
>>> pd.Series([1.1]).isin(['1.1'])
0    False
dtype: bool
File:      c:\users\anish\anaconda3\lib\site-packages\pandas\core\series.py
Type:      method

In [282]:
mask_1 = sales_data.Product.isin(['Laptop', 'Phone'])
mask_2 = sales_data.Units_Sold > 10

sales_data[(mask_1) & (mask_2)]

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
8,2023-03-16,Phone,North,17,372.73,1029,6336.41
10,2023-01-24,Phone,West,14,1492.51,1018,20895.14
11,2023-01-03,Phone,South,15,408.53,1030,6127.95
15,2023-03-29,Laptop,East,16,545.67,1048,8730.72
17,2023-02-07,Phone,North,18,585.08,1082,10531.44
...,...,...,...,...,...,...,...
475,2023-01-04,Laptop,North,12,1682.09,1085,20185.08
477,2023-01-24,Phone,South,15,1524.14,1054,22862.10
479,2023-01-02,Phone,East,12,1388.92,1092,16667.04
493,2023-03-06,Phone,South,14,155.24,1066,2173.36
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44

In [283]:
mask_1 = (sales_data["Product"] == "Laptop") | (sales_data["Product"] == "Phone")
mask_2 = sales_data["Units_Sold"] > 10
sales_data[mask_1 & mask_2]

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
8,2023-03-16,Phone,North,17,372.73,1029,6336.41
10,2023-01-24,Phone,West,14,1492.51,1018,20895.14
11,2023-01-03,Phone,South,15,408.53,1030,6127.95
15,2023-03-29,Laptop,East,16,545.67,1048,8730.72
17,2023-02-07,Phone,North,18,585.08,1082,10531.44
...,...,...,...,...,...,...,...
475,2023-01-04,Laptop,North,12,1682.09,1085,20185.08
477,2023-01-24,Phone,South,15,1524.14,1054,22862.10
479,2023-01-02,Phone,East,12,1388.92,1092,16667.04
493,2023-03-06,Phone,South,14,155.24,1066,2173.36
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44

### 1.3
**Purpose of the Code Cell**

This code cell extracts specific columns from the sales_data DataFrame while keeping all rows.

**Step by Step Functionality**

The loc indexer is used for label based selection in a DataFrame.

The first argument, :, selects all rows in the dataset.

The second argument is a list of column names. Only the Product, Region, and Total_Sales columns are selected.

In [284]:
sales_data.loc[:, ['Product', 'Region', 'Total_Sales']]
# Use loc to select specific rows and columns from the DataFrame
# : selects all rows
# ['Product', 'Region', 'Total_Sales'] selects only these specified columns


### or sales_data[["Product" , "Region" , "Total_Sales"]]

      Product Region  Total_Sales
0    Keyboard  North     23386.68
1     Monitor  South     18033.15
2       Phone  North      5247.27
3    Keyboard  North     14186.77
4      Tablet  North     11265.60
..        ...    ...          ...
495  Keyboard  South      4445.10
496    Laptop   West     15058.44
497   Monitor  North      9508.62
498    Tablet  South      3522.20
499   Monitor  North     19245.78

[500 rows x 3 columns]

**Purpose of the Code Cell**

This code cell selects specific columns from the DataFrame using their integer index positions.

**Step by Step Functionality**

The iloc indexer is used for position based selection in pandas.

The first argument, :, selects all rows in the dataset.

The second argument is a list of column index positions. Columns at positions 1, 2, and 6 are selected based on their order in the DataFrame, not their names.

This method is useful when column positions are known or when working with numerical indexing rather than label based indexing.

In [285]:
sales_data.iloc[:, [1, 2, 6]]
# Use iloc for position based indexing
# : selects all rows
# [1, 2, 6] selects columns at index positions 1, 2, and 6

      Product Region  Total_Sales
0    Keyboard  North     23386.68
1     Monitor  South     18033.15
2       Phone  North      5247.27
3    Keyboard  North     14186.77
4      Tablet  North     11265.60
..        ...    ...          ...
495  Keyboard  South      4445.10
496    Laptop   West     15058.44
497   Monitor  North      9508.62
498    Tablet  South      3522.20
499   Monitor  North     19245.78

[500 rows x 3 columns]

In [286]:
l = sales_data.columns.to_list()
# Convert the DataFrame column index object into a regular Python list

l.index('Product')
# Find the position of the column name 'Date' inside the list

1

In [287]:
sales_data.columns.get_loc('Date')
# Access the column index object of the DataFrame
# Use get_loc to find the integer position of the column named 'Region'
# Returns the numerical index of the 'Region' column

0

In [288]:
sales_data.columns

Index(['Date', 'Product', 'Region', 'Units_Sold', 'Unit_Price', 'Customer_ID',
       'Total_Sales'],
      dtype='object')

In [289]:
sales_data[['Product', 'Region', 'Total_Sales']]

      Product Region  Total_Sales
0    Keyboard  North     23386.68
1     Monitor  South     18033.15
2       Phone  North      5247.27
3    Keyboard  North     14186.77
4      Tablet  North     11265.60
..        ...    ...          ...
495  Keyboard  South      4445.10
496    Laptop   West     15058.44
497   Monitor  North      9508.62
498    Tablet  South      3522.20
499   Monitor  North     19245.78

[500 rows x 3 columns]

### 2.1 Find the total sales by product

 **Grouping Operations**:
   - Find the total sales by product
   - Calculate the average units sold by region
   - Find the top 3 customers by total spending

In [290]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

In [291]:
sales_data.Product.unique()

array(['Keyboard', 'Monitor', 'Phone', 'Tablet', 'Laptop'], dtype=object)

In [292]:
product_groups = sales_data.groupby('Product')
product_groups  ## gropus by product name

In [293]:
product_groups[["Total_Sales" , "Units_Sold"]].sum()
# product_groups[[['Total_Sales', "Units_Sold"]].sum()  # multiple columns

# Group the DataFrame by the 'Product' column
# Select the 'Total_Sales' column from each group
# Calculate the sum of Total_Sales for each product

          Total_Sales  Units_Sold
Product
Keyboard   1074551.96        1064
Laptop     1199835.35        1108
Monitor     950987.34         920
Phone       959547.49         992
Tablet      988081.01         943

### 2.3 Find the top 3 customers by total spending

In [294]:
sales_data.Customer_ID.unique()  ## how many unique customers have made a purchase

array([1002, 1087, 1079, 1057, 1054, 1003, 1023, 1033, 1029, 1081, 1018,
       1030, 1059, 1048, 1062, 1082, 1021, 1075, 1099, 1063, 1047, 1044,
       1093, 1096, 1017, 1091, 1046, 1074, 1056, 1032, 1016, 1069, 1019,
       1090, 1014, 1077, 1008, 1089, 1015, 1068, 1060, 1009, 1049, 1076,
       1080, 1050, 1041, 1034, 1045, 1025, 1092, 1036, 1083, 1020, 1073,
       1004, 1038, 1000, 1040, 1053, 1088, 1035, 1084, 1085, 1006, 1013,
       1094, 1043, 1072, 1055, 1067, 1031, 1070, 1086, 1011, 1097, 1027,
       1042, 1064, 1001, 1065, 1039, 1037, 1058, 1098, 1078, 1026, 1024,
       1071, 1005, 1051, 1022, 1010, 1007, 1012, 1061, 1066, 1052])

In [295]:
sales_data.Customer_ID.value_counts()  # how many time each customer has made a purchase

Customer_ID
1069    12
1018    10
1032     9
1020     9
1091     9
        ..
1078     2
1055     1
1012     1
1017     1
1064     1
Name: count, Length: 98, dtype: int64

In [296]:
customer_groups = sales_data.groupby('Customer_ID')

In [297]:
total_purchase_by_customer = customer_groups['Total_Sales'].sum().sort_values(ascending=False)
total_purchase_by_customer

Customer_ID
1047    127658.62
1013    124894.36
1063    121376.18
1085    106438.14
1034    105255.55
          ...
1064     11376.84
1017      9147.48
1053      8879.71
1012      6021.82
1066      4486.09
Name: Total_Sales, Length: 98, dtype: float64

In [298]:
total_purchase_by_customer.head(3)

Customer_ID
1047    127658.62
1013    124894.36
1063    121376.18
Name: Total_Sales, dtype: float64

In [299]:
total_purchase_by_customer.nlargest(5)

Customer_ID
1047    127658.62
1013    124894.36
1063    121376.18
1085    106438.14
1034    105255.55
Name: Total_Sales, dtype: float64

## 2.2 Calculate the average units sold by region

In [300]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

In [301]:
sales_data.groupby("Region")["Units_Sold"].mean()

Region
East      9.875000
North    10.395522
South     9.968504
West      9.945946
Name: Units_Sold, dtype: float64

**Filtering**:
   - Find all sales above $5000
   - Find the most expensive single sale for each product
   - Find all sales that occurred on weekends

### 3.3 Find all sales that occurred on weekends

In [302]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

In [303]:
# pd.to_datetime()

In [304]:
sales_data['Date'].dt.dayofweek ## 0 means sunday

0      1
1      6
2      0
3      3
4      5
      ..
495    3
496    2
497    6
498    0
499    6
Name: Date, Length: 500, dtype: int32

In [305]:
sundays = sales_data['Date'].dt.dayofweek == 0
sundays

0      False
1      False
2       True
3      False
4      False
       ...
495    False
496    False
497    False
498     True
499    False
Name: Date, Length: 500, dtype: bool

In [306]:
sales_data[sundays]  ## data of sales on sundays

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
14,2023-01-02,Tablet,North,19,396.71,1018,7537.49
16,2023-01-30,Monitor,South,8,1930.36,1062,15442.88
18,2023-01-02,Keyboard,South,18,1357.10,1021,24427.80
24,2023-02-27,Laptop,North,17,1742.76,1099,29626.92
...,...,...,...,...,...,...,...
476,2023-01-16,Keyboard,North,15,120.96,1040,1814.40
479,2023-01-02,Phone,East,12,1388.92,1092,16667.04
489,2023-02-20,Tablet,North,5,361.86,1020,1809.30
493,2023-03-06,Phone,South,14,155.24,1066,2173.36
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20

**Apply Functions**:
   - Create a new column 'Price_Category' that labels each sale as:
     - 'Budget' if Unit_Price < 300
     - 'Mid-Range' if 300 ≤ Unit_Price < 1000
     - 'Premium' if Unit_Price ≥ 1000

### 4 Create a new column 'Price_Category' that labels each sale as:
     - 'Budget' if Unit_Price < 300
     - 'Mid-Range' if 300 ≤ Unit_Price < 1000
     - 'Premium' if Unit_Price ≥ 1000

In [307]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

In [308]:
sales_data["Unit_Price"]

0      1948.89
1      1202.21
2       583.03
3      1091.29
4       751.04
        ...
495     444.51
496     836.58
497     864.42
498    1761.10
499    1069.21
Name: Unit_Price, Length: 500, dtype: float64

- **Apply on Series**  When you select a single column/Row (which is a Series) or create a standalone Series, .apply() operates element-wise. The function you pass receives individual data values, one at a time. Example : 
```python
         df['score'].apply(lambda x: x * 10)`  
```

- **Apply on DataFrame**  When you call .apply() on an entire DataFrame, it processes data row-wise or column-wise. The function you pass receives a whole Series representing that entire row or column. DOCs [1](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html), [2](https://www.digitalocean.com/community/tutorials/pandas-dataframe-apply-examples)

- Example of using .apply() on a DataFrame:

```python
         # Finds the maximum value of each column (default is axis=0, which means column-wise)
         df.apply(lambda col: col.max(), axis=0) 

         # Adds values from Column_A and Column_B together for every row
         df.apply(lambda row: row['Column_A'] + row['Column_B'], axis=1)
```

In [309]:
def price_cat(u_price):

  if u_price <300:
    return 'Budget'
  elif u_price >= 300 and u_price < 1000:
    return 'Mid-Range'
  else:
    return 'Premium'

In [310]:
Price_Category_sr = sales_data['Unit_Price'].apply(func=price_cat)  ## axis = 1 means row wise
Price_Category_sr

0        Premium
1        Premium
2      Mid-Range
3        Premium
4      Mid-Range
         ...
495    Mid-Range
496    Mid-Range
497    Mid-Range
498      Premium
499      Premium
Name: Unit_Price, Length: 500, dtype: object

In [311]:
sales_data['Price_Category'] = Price_Category_sr 
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales,Price_Category
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68,Premium
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15,Premium
2,2023-03-13,Phone,North,9,583.03,1079,5247.27,Mid-Range
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77,Premium
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60,Mid-Range
...,...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10,Mid-Range
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44,Mid-Range
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62,Mid-Range
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20,Premium
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78,Premium

## Exercise 2: Employee Data Analysis

In [312]:
import pandas as pd
import numpy as np

**Purpose of the Code Cell**

This code cell generates a synthetic employee dataset for analysis, testing, or demonstration purposes.

**Step by Step Functionality**

First, a random seed is set to ensure that the randomly generated data remains consistent across multiple runs.

Two lists are defined to represent possible departments and job positions.

A DataFrame named employee_data is created with 50 employees. The columns include:

Employee_ID generated as a sequential numeric range.

Name generated dynamically using formatted strings.

Department and Position randomly assigned from predefined lists.

Salary generated as random integers within a realistic salary range.

Join_Date randomly selected from a date range between 2018 and 2023 and converted into datetime format.

Performance_Score generated as random integers between 1 and 100.

In [313]:
# Create sample employee data

np.random.seed(42)
# Set random seed to ensure reproducibility of random values

departments = ['Engineering', 'Marketing', 'Finance', 'HR', 'Sales']
# Define a list of department names

positions = ['Junior', 'Mid', 'Senior', 'Manager', 'Director']
# Define a list of job position levels

employee_data = pd.DataFrame({
    'Employee_ID': range(1001, 1051),
    # Generate sequential employee IDs from 1001 to 1050

    'Name': [f'Employee_{i}' for i in range(1, 51)],
    # Create employee names using list comprehension

    'Department': np.random.choice(departments, 50),
    # Randomly assign one of the departments to each employee

    'Position': np.random.choice(positions, 50),
    # Randomly assign one of the job positions to each employee

    'Salary': np.random.randint(40000, 150000, 50),
    # Generate random salary values between 40000 and 149999

    'Join_Date': pd.to_datetime(
        np.random.choice(pd.date_range('2018-01-01', '2023-01-01'), 50)
    ),
    # Randomly select join dates from a date range and convert to datetime format

    'Performance_Score': np.random.randint(1, 101, 50)
    # Generate random performance scores between 1 and 100
})

In [314]:
employee_data.shape

(50, 7)

In [315]:
sample_data = employee_data.sample(10)
sample_data

,Employee_ID,Name,Department,Position,Salary,Join_Date,Performance_Score
35,1036,Employee_36,Sales,Junior,58141,2019-11-15,59
28,1029,Employee_29,HR,Manager,127897,2022-01-19,98
12,1013,Employee_13,Sales,Director,103335,2022-03-10,19
16,1017,Employee_17,HR,Mid,110592,2018-07-09,90
48,1049,Employee_49,Marketing,Mid,83585,2022-03-14,96
26,1027,Employee_27,Finance,Junior,40206,2021-10-14,24
19,1020,Employee_20,HR,Manager,119309,2021-11-01,32
9,1010,Employee_10,Sales,Mid,119575,2022-12-27,96
23,1024,Employee_24,Engineering,Mid,138806,2020-08-30,56
21,1022,Employee_22,Sales,Director,92992,2019-09-25,55

### Tasks:

1. **Basic Operations**:
   - Find all employees in Engineering with salary > $80,000
   - Count the number of employees in each department
   - Find the average salary by position level

2. **Time-Based Analysis**:
   - Calculate employee tenure in years. Suppose the end date is `'2023-01-01'`
   - Find employees who joined in 2020
   - Calculate the average performance score by year of joining

3. **Advanced Grouping**:
   - For each department, find the highest and lowest salary
   - Find departments where the average performance score is above 70

4. **Apply and Transform**:
   - Apply a 5% salary increase to all employees with performance score > 80

In [316]:
# Solution
sample_data

,Employee_ID,Name,Department,Position,Salary,Join_Date,Performance_Score
35,1036,Employee_36,Sales,Junior,58141,2019-11-15,59
28,1029,Employee_29,HR,Manager,127897,2022-01-19,98
12,1013,Employee_13,Sales,Director,103335,2022-03-10,19
16,1017,Employee_17,HR,Mid,110592,2018-07-09,90
48,1049,Employee_49,Marketing,Mid,83585,2022-03-14,96
26,1027,Employee_27,Finance,Junior,40206,2021-10-14,24
19,1020,Employee_20,HR,Manager,119309,2021-11-01,32
9,1010,Employee_10,Sales,Mid,119575,2022-12-27,96
23,1024,Employee_24,Engineering,Mid,138806,2020-08-30,56
21,1022,Employee_22,Sales,Director,92992,2019-09-25,55

1.1

In [317]:
employee_data[
    (employee_data["Department"] == "Engineering") &
    (employee_data["Salary"] > 80000)
]

,Employee_ID,Name,Department,Position,Salary,Join_Date,Performance_Score
23,1024,Employee_24,Engineering,Mid,138806,2020-08-30,56
33,1034,Employee_34,Engineering,Director,94268,2021-06-02,97
38,1039,Employee_39,Engineering,Manager,111910,2022-08-23,93
45,1046,Employee_46,Engineering,Senior,115450,2019-03-18,67

1.2

In [318]:
employee_data["Department"].value_counts()

Department
HR             13
Sales          10
Finance        10
Marketing      10
Engineering     7
Name: count, dtype: int64

1.3

In [319]:
# grouping by "Position"

Position_groups = employee_data.groupby('Position')

Position_groups["Salary"].mean()

Position
Director    100234.333333
Junior       98803.909091
Manager     101556.076923
Mid         100994.181818
Senior      105959.000000
Name: Salary, dtype: float64

2.1

In [320]:
## Calculate employee tenure in years. Suppose the end date is `'2023-01-01'`

(pd.to_datetime("2023-01-01") - employee_data.Join_Date).dt.days / 365.25

##.dt provides datetime-related operations for a Series.
##.days extracts the day value from each time difference.

0     3.477070
1     0.626968
2     2.228611
3     3.233402
4     2.822724
5     2.121834
6     0.501027
7     0.676249
8     1.267625
9     0.013689
10    1.292266
11    0.446270
12    0.813142
13    1.245722
14    0.903491
15    1.566051
16    4.481862
17    1.582478
18    1.144422
19    1.166324
20    1.423682
21    3.268994
22    3.282683
23    2.338125
24    0.158795
25    1.489391
26    1.215606
27    3.058179
28    0.950034
29    1.073238
30    3.225188
31    4.131417
32    0.344969
33    1.582478
34    1.557837
35    3.129363
36    3.184120
37    1.174538
38    0.358658
39    0.533881
40    0.906229
41    1.560575
42    0.303901
43    1.889117
44    0.837782
45    3.791923
46    3.457906
47    1.464750
48    0.802190
49    1.141684
Name: Join_Date, dtype: float64

2.2

In [321]:
##  Find employees who joined in 2020

mask_2020 = employee_data.Join_Date.dt.year == 2020
employees_joined_2020 = employee_data[mask_2020]
employees_joined_2020

,Employee_ID,Name,Department,Position,Salary,Join_Date,Performance_Score
2,1003,Employee_3,Finance,Manager,48392,2020-10-09,81
4,1005,Employee_5,Sales,Senior,118603,2020-03-06,2
5,1006,Employee_6,Marketing,Junior,92256,2020-11-17,2
23,1024,Employee_24,Engineering,Mid,138806,2020-08-30,56

2.3

In [322]:
### Calculate the average performance score by year of joining
employee_data.groupby(employee_data.Join_Date.dt.year)["Performance_Score"].mean()

Join_Date
2018    50.500000
2019    56.200000
2020    35.250000
2021    54.611111
2022    52.500000
Name: Performance_Score, dtype: float64

3.1

In [323]:
# For each department, find the highest and lowest salary
salary_summary = employee_data.groupby("Department")["Salary"].agg(
    ["max", "min", "mean"]
)

salary_summary

                max    min           mean
Department
Engineering  138806  46910   89897.285714
Finance      130982  40206  100489.200000
HR           149225  63419  109741.615385
Marketing    148066  50965  102301.900000
Sales        145878  58141   97203.800000

3.2

In [324]:
### Find departments where the average performance score is above 70

department_gp = employee_data.groupby("Department")
Performance_Score_mean_by_department =department_gp["Performance_Score"].mean()
Performance_Score_mean_by_department

Department
Engineering    65.571429
Finance        60.600000
HR             51.692308
Marketing      41.200000
Sales          47.800000
Name: Performance_Score, dtype: float64

In [325]:
Performance_Score_mean_by_department > 70

Department
Engineering    False
Finance        False
HR             False
Marketing      False
Sales          False
Name: Performance_Score, dtype: bool

4.1

In [326]:

### Apply a 5% salary increase to all employees with performance score > 80

employee_data["New_Salary"] = employee_data["Salary"]


performance_mask = employee_data["Performance_Score"] > 80
employee_data.loc[performance_mask, "New_Salary"] = employee_data.loc[performance_mask, "Salary"] * 1.05

employee_data


# or using apply()

def apply_salary_increase_by_row(row):
    if row["Performance_Score"] > 80:
        return row["Salary"] * 1.05
    else:
        return row["Salary"]
    
employee_data["New_Salary"] = employee_data.apply(apply_salary_increase_by_row, axis=1)

employee_data

C:\Users\anish\AppData\Local\Temp\ipykernel_13412\688749217.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 50811.6  135591.75 123241.65 125553.75 143171.7  116121.6  134291.85
  95167.8   98981.4  117505.5  127820.7   87764.25]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  employee_data.loc[performance_mask, "New_Salary"] = employee_data.loc[performance_mask, "Salary"] * 1.05

,Employee_ID,Name,Department,Position,Salary,Join_Date,Performance_Score,New_Salary
0,1001,Employee_1,HR,Manager,92251,2019-07-11,3,92251.00
1,1002,Employee_2,Sales,Manager,62662,2022-05-17,56,62662.00
2,1003,Employee_3,Finance,Manager,48392,2020-10-09,81,50811.60
3,1004,Employee_4,Sales,Director,70535,2019-10-08,59,70535.00
4,1005,Employee_5,Sales,Senior,118603,2020-03-06,2,118603.00
5,1006,Employee_6,Marketing,Junior,92256,2020-11-17,2,92256.00
6,1007,Employee_7,Finance,Manager,129135,2022-07-02,92,135591.75
7,1008,Employee_8,Finance,Mid,75222,2022-04-29,54,75222.00
8,1009,Employee_9,Finance,Manager,117373,2021-09-25,87,123241.65
9,1010,Employee_10,Sales,Mid,119575,2022-12-27,96,125553.75
10,1011,Employee_11,HR,Mid,136354,2021-09-16,97,143171.70
11,1012,Employee_12,Finance,Manager,124651,2022-07-22,1,124651.00
12,1013,Employee_13,Sales,Director,103335,2022-03-10,19,103335.00
13,1014,Employee_14,Marketing,Mid,50965,2021-10-03,2,50965.00
14,1015,Employee_15,HR,Mid,64538,2022-02-05,53,64538.00
15,1016,Employee_16,Marketing,Manager,148066,2021-06-08,44,148066.00
16,1017,Employee_17,HR,Mid,110592,2018-07-09,90,116121.60
17,1018,Employee_18,Sales,Mid,138018,2021-06-02,32,138018.00
18,1019,Employee_19,Engineering,Manager,48110,2021-11-09,70,48110.00
19,1020,Employee_20,HR,Manager,119309,2021-11-01,32,119309.00
20,1021,Employee_21,Marketing,Junior,67266,2021-07-30,68,67266.00
21,1022,Employee_22,Sales,Director,92992,2019-09-25,55,92992.00
22,1023,Employee_23,HR,Director,122948,2019-09-20,75,122948.00
23,1024,Employee_24,Engineering,Mid,138806,2020-08-30,56,138806.00
24,1025,Employee_25,Engineering,Director,46910,2022-11-04,17,46910.00
25,1026,Employee_26,Finance,Mid,130982,2021-07-06,38,130982.00
26,1027,Employee_27,Finance,Junior,40206,2021-10-14,24,40206.00
27,1028,Employee_28,Marketing,Manager,127054,2019-12-11,69,127054.00
28,1029,Employee_29,HR,Manager,127897,2022-01-19,98,134291.85
29,1030,Employee_30,HR,Manager,63419,2021-12-05,70,63419.00
30,1031,Employee_31,Finance,Director,90636,2019-10-11,86,95167.80
31,1032,Employee_32,HR,Junior,90015,2018-11-14,11,90015.00
32,1033,Employee_33,HR,Director,147059,2022-08-28,16,147059.00
33,1034,Employee_34,Engineering,Director,94268,2021-06-02,97,98981.40
34,1035,Employee_35,Finance,Junior,127939,2021-06-11,73,127939.00
35,1036,Employee_36,Sales,Junior,58141,2019-11-15,59,58141.00
36,1037,Employee_37,Finance,Junior,120356,2019-10-26,70,120356.00
37,1038,Employee_38,Sales,Junior,145878,2021-10-29,80,145878.00
38,1039,Employee_39,Engineering,Manager,111910,2022-08-23,93,117505.50
39,1040,Employee_40,Marketing,Senior,96044,2022-06-20,3,96044.00
40,1041,Employee_41,HR,Senior,107214,2022-02-04,20,107214.00
41,1042,Employee_42,Engineering,Junior,73827,2021-06-10,59,73827.00
42,1043,Employee_43,HR,Senior,95820,2022-09-12,36,95820.00
43,1044,Employee_44,Marketing,Senior,102623,2021-02-10,19,102623.00
44,1045,Employee_45,Marketing,Junior,121734,2022-03-01,90,127820.70
45,1046,Employee_46,Engineering,Senior,115450,2019-03-18,67,115450.00
46,1047,Employee_47,Marketing,Director,133426,2019-07-18,19,133426.00
47,1048,Employee_48,Sales,Mid,62299,2021-07-15,20,62299.00
48,1049,Employee_49,Marketing,Mid,83585,2022-03-14,96,87764.25
49,1050,Employee_50,HR,Junior,149225,2021-11-10,71,149225.00

## Exercise 3: Customer Behavior Analysis

In [327]:
np.random.seed(42)  # Set a seed for reproducibility

customers = pd.DataFrame({
    'Customer_ID': range(1000, 1020),
    # Create 20 sequential customer IDs from 1000 to 1019

    'Age': np.random.randint(18, 70, 20),
    # Generate 20 random ages between 18 and 69

    'Gender': np.random.choice(['M', 'F'], 20),
    # Randomly assign gender M or F to 20 customers

    'Income': np.random.choice(['Low', 'Medium', 'High'], 20, p=[0.4, 0.5, 0.1]),
    # Randomly assign income category with specified probabilities
    # 40 percent Low, 50 percent Medium, 10 percent High

    'Join_Date': pd.to_datetime(
        np.random.choice(pd.date_range('2020-01-01', '2023-01-01'), 20)
    )
    # Randomly select 20 join dates from a date range and convert to datetime
})


transactions = pd.DataFrame({
    'Transaction_ID': range(5000, 5100),
    # Create 100 sequential transaction IDs from 5000 to 5099

    'Customer_ID': np.random.choice(customers['Customer_ID'], 100),
    # Randomly assign one of the existing customer IDs to each transaction

    'Date': pd.to_datetime(
        np.random.choice(pd.date_range('2023-01-01', '2023-03-31'), 100)
    ),
    # Randomly select 100 transaction dates from the given range

    'Amount': np.random.uniform(5, 500, 100).round(2),
    # Generate 100 random transaction amounts between 5 and 500 rounded to 2 decimals

    'Category': np.random.choice(
        ['Electronics', 'Clothing', 'Groceries', 'Entertainment'], 100
    )
    # Randomly assign a purchase category to each transaction
})

In [328]:
customers.head()

   Customer_ID  Age Gender  Income  Join_Date
0         1000   56      F     Low 2020-02-04
1         1001   69      F     Low 2020-07-24
2         1002   46      F  Medium 2022-10-22
3         1003   32      F  Medium 2022-10-18
4         1004   60      F     Low 2021-07-19

In [329]:
transactions.head()

   Transaction_ID  Customer_ID       Date  Amount       Category
0            5000         1012 2023-02-28  157.49       Clothing
1            5001         1008 2023-01-02  273.56  Entertainment
2            5002         1014 2023-01-02  256.86    Electronics
3            5003         1012 2023-02-23  319.98  Entertainment
4            5004         1000 2023-03-28  128.98    Electronics

In [330]:
pd.merge?

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null value, those
    rows will be matched against each other. This is different from usual SQL
    join behaviour and can lead to unexpected results.

Parameters
----------
left : DataFrame or named Series
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.
on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default True
    If False, avoid copy if possible.

    .. note::
        The `copy` keyword will change behavior in pandas 3.0.
        `Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        will be enabled by default, which means that all methods with a
        `copy` keyword will use a lazy copy mechanism to defer the copy and
        ignore the `copy` keyword. The `copy` keyword will be removed in a
        future version of pandas.

        You can already get the future behavior and improvements through
        enabling copy on write ``pd.options.mode.copy_on_write = True``
indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Examples
--------
>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  bar        2  bar        6
3  baz        3  baz        7
4  foo        5  foo        5
5  foo        5  foo        8

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  bar           2  bar            6
3  baz           3  baz            7
4  foo           5  foo            5
5  foo           5  foo            8

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='object')

>>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
>>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
>>> df1
      a  b
0   foo  1
1   bar  2
>>> df2
      a  c
0   foo  3
1   baz  4

>>> df1.merge(df2, how='inner', on='a')
      a  b  c
0   foo  1  3

>>> df1.merge(df2, how='left', on='a')
      a  b  c
0   foo  1  3.0
1   bar  2  NaN

>>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
>>> df2 = pd.DataFrame({'right': [7, 8]})
>>> df1
    left
0   foo
1   bar
>>> df2
    right
0   7
1   8

>>> df1.merge(df2, how='cross')
   left  right
0   foo      7
1   foo      8
2   bar      7
3   bar      8
File:      c:\users\anish\anaconda3\lib\site-packages\pandas\core\reshape\merge.py
Type:      function


### Tasks:

1. **Data Merging**:
   - Merge customer data with transaction data
   - Find customers with no transactions (left join)

2. **Customer Segmentation**:
   - Group customers by age brackets (18-25, 26-35, etc.) and analyze spending
   - Calculate average transaction amount by income level

In [331]:
# Left DataFrame (df1)       Right DataFrame (df2)
# +------------+-----+       +------------+-------+
# | customer_id| val |       | customer_id| val2  |
# +------------+-----+       +------------+-------+
# |     1      |  A  |       |     1      |   X   |
# |     2      |  B  |       |     3      |   Y   |
# |     3      |  C  |       |     4      |   Z   |
# +------------+-----+       +------------+-------+

In [332]:
df1 = pd.DataFrame({
    'c_id' : [1,2,3],
    'val' : ['A', 'B', 'C']

})

df2 = pd.DataFrame({
    'c_id' : [1,3,4],
    'val' : ['X', 'Y', 'Z']
})

In [333]:
df1

   c_id val
0     1   A
1     2   B
2     3   C

In [334]:
df2

   c_id val
0     1   X
1     3   Y
2     4   Z

In [335]:
merged_df = pd.merge(df1, df2, how='left', on='c_id')

In [336]:
merged_df

   c_id val_x val_y
0     1     A     X
1     2     B   NaN
2     3     C     Y

In [344]:
val_y_absent_mask  = merged_df['val_y'].isna()
val_y_absent_mask

0    False
1     True
2    False
Name: val_y, dtype: bool

In [345]:
merged_df[val_y_absent_mask]

   c_id val_x val_y
1     2     B   NaN

In [339]:
pd.merge?

# Parameters
# ----------
# left : DataFrame or named Series
# right : DataFrame or named Series
#     Object to merge with.
# how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
#     Type of merge to be performed.

#     * left: use only keys from left frame, similar to a SQL left outer join;
#       preserve key order.
#     * right: use only keys from right frame, similar to a SQL right outer join;
#       preserve key order.
#     * outer: use union of keys from both frames, similar to a SQL full outer
#       join; sort keys lexicographically.
#     * inner: use intersection of keys from both frames, similar to a SQL inner
#       join; preserve the order of the left keys.
#     * cross: creates the cartesian product from both frames, preserves the order
#       of the left keys.
# on : label or list
#     Column or index level names to join on. These must be found in both
#     DataFrames. If `on` is None and not merging on indexes then this defaults
#     to the intersection of the columns in both DataFrames.
# left_on : label or list, or array-like

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null value, those
    rows will be matched against each other. This is different from usual SQL
    join behaviour and can lead to unexpected results.

Parameters
----------
left : DataFrame or named Series
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.
on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default True
    If False, avoid copy if possible.

    .. note::
        The `copy` keyword will change behavior in pandas 3.0.
        `Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        will be enabled by default, which means that all methods with a
        `copy` keyword will use a lazy copy mechanism to defer the copy and
        ignore the `copy` keyword. The `copy` keyword will be removed in a
        future version of pandas.

        You can already get the future behavior and improvements through
        enabling copy on write ``pd.options.mode.copy_on_write = True``
indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Examples
--------
>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  bar        2  bar        6
3  baz        3  baz        7
4  foo        5  foo        5
5  foo        5  foo        8

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  bar           2  bar            6
3  baz           3  baz            7
4  foo           5  foo            5
5  foo           5  foo            8

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='object')

>>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
>>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
>>> df1
      a  b
0   foo  1
1   bar  2
>>> df2
      a  c
0   foo  3
1   baz  4

>>> df1.merge(df2, how='inner', on='a')
      a  b  c
0   foo  1  3

>>> df1.merge(df2, how='left', on='a')
      a  b  c
0   foo  1  3.0
1   bar  2  NaN

>>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
>>> df2 = pd.DataFrame({'right': [7, 8]})
>>> df1
    left
0   foo
1   bar
>>> df2
    right
0   7
1   8

>>> df1.merge(df2, how='cross')
   left  right
0   foo      7
1   foo      8
2   bar      7
3   bar      8
File:      c:\users\anish\anaconda3\lib\site-packages\pandas\core\reshape\merge.py
Type:      function

In [346]:
merged_data = pd.merge(customers, transactions, how ='left', on='Customer_ID')

In [347]:
merged_data

,Customer_ID,Age,Gender,Income,Join_Date,Transaction_ID,Date,Amount,Category
0,1000,56,F,Low,2020-02-04,5004.0,2023-03-28,128.98,Electronics
1,1000,56,F,Low,2020-02-04,5007.0,2023-01-02,245.94,Entertainment
2,1000,56,F,Low,2020-02-04,5016.0,2023-03-16,288.14,Groceries
3,1000,56,F,Low,2020-02-04,5026.0,2023-03-14,278.62,Entertainment
4,1000,56,F,Low,2020-02-04,5033.0,2023-02-05,245.21,Entertainment
...,...,...,...,...,...,...,...,...,...
96,1019,41,F,Medium,2022-12-12,5051.0,2023-01-31,131.82,Electronics
97,1019,41,F,Medium,2022-12-12,5068.0,2023-01-03,420.27,Entertainment
98,1019,41,F,Medium,2022-12-12,5073.0,2023-01-24,270.86,Entertainment
99,1019,41,F,Medium,2022-12-12,5088.0,2023-02-10,202.42,Entertainment
100,1019,41,F,Medium,2022-12-12,5091.0,2023-02-02,129.18,Electronics

In [348]:
merged_data.isna()

,Customer_ID,Age,Gender,Income,Join_Date,Transaction_ID,Date,Amount,Category
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
96,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False
100,False,False,False,False,False,False,False,False,False

In [343]:
merged_data.isna().sum()

Customer_ID       0
Age               0
Gender            0
Income            0
Join_Date         0
Transaction_ID    1
Date              1
Amount            1
Category          1
dtype: int64