# graded_assignment 1.2

#### General Instruction
- A) Shape of the dataset is (10000, 12) [Please note that if you do not obtain this shape, it may indicate that the data was not uploaded correctly into the Colab environment.]
- B) For simplicity please consider all the unknown values ("?") as null values for this assignment.
- C) Consider each question as individual question unless instructed otherwise and use the given csv data to compute all the solutions.

In [168]:
import pandas as pd
import numpy as np

In [169]:
df = pd.read_csv("Week1_GA_dataset.csv")

In [170]:
df.shape

(10000, 12)

- `axis=0` means the operation moves vertically down the rows. It collapses the rows to give you one result per column. (data is processed column-wise)
- `axis=1` means the operation moves horizontally across the columns. It collapses the columns to give you one result per row. (data is processed row-wise)

In [171]:
count_of_nulls = (df == "?").sum().sum()
print(f"Count of nulls in the dataset: {count_of_nulls}")
df.replace('?', np.nan, inplace=True)
df

Count of nulls in the dataset: 1823

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [172]:
df.iloc[692, 0]

'2009-11-16'

In [173]:
df.iloc[546, 7]

3

In [174]:
# What are the unique values present in the Locality feature of the dataset?

df["Locality"].dropna().unique() ## not include nan values in the unique count with help of dropna()

array(['Waterbury', 'Bridgeport', 'Greenwich', 'Norwalk', 'Fairfield',
       'West Hartford', 'Stamford'], dtype=object)

In [175]:
# Which of the following features have missing(NaN) values present in the dataset?
df.isnull().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

In [176]:
# Which of the following feature has most missing(NaN) values present in the dataset?
df.isnull().sum().sort_values(ascending=False).head(1)

Property    1823
dtype: int64

In [177]:
# Drop all the samples(rows) with missing values strictly greater than 2. How many samples remains after that ?
df[~(df.isnull().sum(axis=1) > 2)].shape

(9917, 12)

In [178]:
# Drop all the samples(rows) with missing values in the original dataframe. How many samples remains after that ?

df.dropna().shape

(5449, 12)

# graded_assignment 1.2

#### General Instruction
- A) Shape of the dataset is (10000, 12) [Please note that if you do not obtain this shape, it may indicate that the data was not uploaded correctly into the Colab environment.]
- B) For simplicity please consider all the unknown values ("?") as null values for this assignment.
- C) Consider each question as individual question unless instructed otherwise and use the given csv data to compute all the solutions.

In [196]:
import pandas as pd
import numpy as np

In [197]:

df = pd.read_csv('Week1_GA_dataset.csv')
df.replace('?', np.nan, inplace=True)

In [198]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East

In [182]:
# Select all the even indexed rows from the given dataset. What is the value in the 3rd indexed column of the 0th indexed row in the selected dataframe. (row/ column indexed from zero(0) in python/pandas)

df.iloc[::2].iloc[0, 3]

111440.0

In [183]:
# Select all the even indexed rows from the given dataset. What is the value in the 3rd indexed column of the 332th indexed row in the selected dataframe. (row/ column indexed from zero(0))

df.iloc[::2].iloc[332, 3]

256200.0

In [184]:
# Select all the odd indexed rows from the given dataset. What is the value in the 3rd indexed column of the 332th indexed row in the selected dataframe. (row/ column indexed from zero(0))
#   Please consider case sensitivity while giving your solution capital letter ≠ small letter
#   If it is a string don't write quotes in the solution.

df.iloc[1::2].iloc[332, 3]

352940.0

In [185]:
# Select all the odd indexed columns from the given dataset. What is the value in the 5th indexed column of the 100th indexed row in the selected dataframe. (row/ column indexed from zero(0))
# Please consider case sensitivity while giving your solution capital letter ≠ small letter
# If it is a string don't write quotes in the solution.

df.iloc[1::2 ].iloc[100, 5]

'Single Family'

In [186]:
# Select all the even indexed columns and even indexed rows from the given dataset. What is the value in the 3th indexed column of the 255th indexed row in the selected dataframe. (row/ column indexed/starts from zero(0))
# Please consider case sensitivity while giving your solution capital letter ≠ small letter
# If it is a string don't write quotes in the solution.

df.iloc[::2, ::2].iloc[255, 3]

'Detached House'

In [187]:
# Determine the number of samples (rows) in the dataset that belong to the six most recent years, based on the provided data.

recent_years = sorted(df['Year'].unique())[-6:]

count = df[df['Year'].isin(recent_years)].shape[0]

print(count)

4749

In [188]:
# Determine the number of samples (rows) in the dataset which has num_rooms = 3 and num_bathrooms = 3

count = df[(df["num_rooms"] == 3) & (df["num_bathrooms"] == 3)].shape[0]
count

2730

In [189]:
# Determine the number of samples (rows) in the dataset which has num_rooms = 3 or num_bathrooms = 3
count = df[(df["num_rooms"] == 3) | (df["num_bathrooms"] == 3)].shape[0]
count

8591

In [190]:
# In the Year 2022, how many houses (rows) located in the Greenwich Locality have exactly num_room == 3, and facing towards either the North or East?
count = df[
    (df['Year'] == 2022) &
    (df['Locality'] == 'Greenwich') &
    (df['num_rooms'] == 3) &
    (df['Face'].isin(['North', 'East']))
].shape[0]

print(count)

42

In [192]:
df["Date"] = pd.to_datetime(df["Date"] , format="%Y-%m-%d")

In [193]:
# Calculate the number of samples(rows) that correspond to the month of August across all the years.?

count = (df['Date'].dt.month == 8).sum()

print(count)

1050

In [ ]:
#  According to the data which Locality have highest average Sale Price?


df[df["Locality"] == "Waterbury"]

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
16,2009-01-05,2009,Waterbury,74620.0,206500.0,Single Family,Detached House,3,3,966.0,1.025953,South
17,2009-01-05,2009,Waterbury,51450.0,187900.0,Three Family,Triplex,6,5,1825.0,1.025953,North
25,2009-01-08,2009,Waterbury,56070.0,75000.0,Two Family,Duplex,4,2,1373.0,1.025953,West
...,...,...,...,...,...,...,...,...,...,...,...,...
9944,2022-09-16,2022,Waterbury,102850.0,179000.0,Single Family,Detached House,3,3,NaN,1.003979,North
9947,2022-09-17,2022,Waterbury,77780.0,73555.0,NaN,Detached House,3,1,1085.0,1.003979,North
9964,2022-09-22,2022,Waterbury,45360.0,20000.0,Two Family,Duplex,4,3,NaN,1.003979,West
9975,2022-09-25,2022,Waterbury,86030.0,150000.0,Single Family,Detached House,3,3,933.0,1.003979,South
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South

In [195]:
avg_price = df.groupby('Locality')['Sale Price'].mean()
avg_price.idxmax()

'Greenwich'